### ISSUE TITLE
How to treat the edge cases?

### ISSUE THREAD

**Issue by chediBechikh** [thesofakillers/dlml-tutorial#1]
Hi

I don't understand why after calculating upper_cdf , lower_cdf, we used the relation between the sigmoid and softplus, I don't see in the formula any softplus.
can you please explain how we obtained this line

```
# log probability for edge case of 0 (before scaling)
low_bound_log_prob = upper_bound_in - F.softplus(upper_bound_in)
```

**Comment by thesofakillers** [comment]
Hey. This is a good question and I agree it's not well explained in the tutorial. I will write something up tomorrow if I find the time.

**Comment by thesofakillers** [comment]
Hey @chediBechikh, I have added a bit more detail in [The How](https://github.com/thesofakillers/dlml-tutorial/blob/main/README.md#the-how) section regarding how we implement the edge cases. From "Let's go line by line" to "in lines 7 through 9". 

The [blogpost](https://www.giuliostarace.com/posts/dlml-tutorial/) is also updated to reflect this

Closing this now! thx
